package com.etc.entity;

public class Academy {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column academy.id
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column academy.aname
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	private String aname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column academy.id
	 * @return  the value of academy.id
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column academy.id
	 * @param id  the value for academy.id
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column academy.aname
	 * @return  the value of academy.aname
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	public String getAname() {
		return aname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column academy.aname
	 * @param aname  the value for academy.aname
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	public void setAname(String aname) {
		this.aname = aname;
	}
}