package com.etc.entity;

import java.util.Date;

public class Classes {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classes.id
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classes.cname
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	private String cname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classes.tid
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	private Integer tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classes.timeTag
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	private Integer timetag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classes.machineTag
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	private Integer machinetag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classes.startDate
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	private Date startdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classes.endDate
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	private Date enddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column classes.studentCount
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	private Integer studentcount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classes.id
	 * @return  the value of classes.id
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classes.id
	 * @param id  the value for classes.id
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classes.cname
	 * @return  the value of classes.cname
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public String getCname() {
		return cname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classes.cname
	 * @param cname  the value for classes.cname
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public void setCname(String cname) {
		this.cname = cname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classes.tid
	 * @return  the value of classes.tid
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public Integer getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classes.tid
	 * @param tid  the value for classes.tid
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public void setTid(Integer tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classes.timeTag
	 * @return  the value of classes.timeTag
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public Integer getTimetag() {
		return timetag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classes.timeTag
	 * @param timetag  the value for classes.timeTag
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public void setTimetag(Integer timetag) {
		this.timetag = timetag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classes.machineTag
	 * @return  the value of classes.machineTag
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public Integer getMachinetag() {
		return machinetag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classes.machineTag
	 * @param machinetag  the value for classes.machineTag
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public void setMachinetag(Integer machinetag) {
		this.machinetag = machinetag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classes.startDate
	 * @return  the value of classes.startDate
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public Date getStartdate() {
		return startdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classes.startDate
	 * @param startdate  the value for classes.startDate
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classes.endDate
	 * @return  the value of classes.endDate
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public Date getEnddate() {
		return enddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classes.endDate
	 * @param enddate  the value for classes.endDate
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column classes.studentCount
	 * @return  the value of classes.studentCount
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public Integer getStudentcount() {
		return studentcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column classes.studentCount
	 * @param studentcount  the value for classes.studentCount
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public void setStudentcount(Integer studentcount) {
		this.studentcount = studentcount;
	}
}