package com.etc.entity;

import java.util.Date;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.id
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.cname
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.tid
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.timeTag
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    private Integer timetag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.machineTag
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    private Integer machinetag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.startDate
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.endDate
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.studentCount
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    private Integer studentcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.id
     *
     * @return the value of class.id
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.id
     *
     * @param id the value for class.id
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.cname
     *
     * @return the value of class.cname
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.cname
     *
     * @param cname the value for class.cname
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.tid
     *
     * @return the value of class.tid
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.tid
     *
     * @param tid the value for class.tid
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.timeTag
     *
     * @return the value of class.timeTag
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public Integer getTimetag() {
        return timetag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.timeTag
     *
     * @param timetag the value for class.timeTag
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public void setTimetag(Integer timetag) {
        this.timetag = timetag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.machineTag
     *
     * @return the value of class.machineTag
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public Integer getMachinetag() {
        return machinetag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.machineTag
     *
     * @param machinetag the value for class.machineTag
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public void setMachinetag(Integer machinetag) {
        this.machinetag = machinetag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.startDate
     *
     * @return the value of class.startDate
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.startDate
     *
     * @param startdate the value for class.startDate
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.endDate
     *
     * @return the value of class.endDate
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.endDate
     *
     * @param enddate the value for class.endDate
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.studentCount
     *
     * @return the value of class.studentCount
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public Integer getStudentcount() {
        return studentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.studentCount
     *
     * @param studentcount the value for class.studentCount
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    public void setStudentcount(Integer studentcount) {
        this.studentcount = studentcount;
    }
}