package com.etc.entity;

public class Teacher {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.id
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.tnumber
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	private Integer tnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.tname
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	private String tname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.aid
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	private Integer aid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.pwd
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	private String pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.email
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	private String email;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.id
	 * @return  the value of teacher.id
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.id
	 * @param id  the value for teacher.id
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.tnumber
	 * @return  the value of teacher.tnumber
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public Integer getTnumber() {
		return tnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.tnumber
	 * @param tnumber  the value for teacher.tnumber
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public void setTnumber(Integer tnumber) {
		this.tnumber = tnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.tname
	 * @return  the value of teacher.tname
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public String getTname() {
		return tname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.tname
	 * @param tname  the value for teacher.tname
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public void setTname(String tname) {
		this.tname = tname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.aid
	 * @return  the value of teacher.aid
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public Integer getAid() {
		return aid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.aid
	 * @param aid  the value for teacher.aid
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public void setAid(Integer aid) {
		this.aid = aid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.pwd
	 * @return  the value of teacher.pwd
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.pwd
	 * @param pwd  the value for teacher.pwd
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.email
	 * @return  the value of teacher.email
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.email
	 * @param email  the value for teacher.email
	 * @mbggenerated  Fri Jul 20 21:05:12 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}
}