package com.etc.dao;

import com.etc.entity.Academy;
import com.etc.entity.AcademyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AcademyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    int countByExample(AcademyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    int deleteByExample(AcademyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    int insert(Academy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    int insertSelective(Academy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    List<Academy> selectByExample(AcademyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    Academy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") Academy record, @Param("example") AcademyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    int updateByExample(@Param("record") Academy record, @Param("example") AcademyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    int updateByPrimaryKeySelective(Academy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table academy
     *
     * @mbggenerated Thu Jul 19 10:15:56 CST 2018
     */
    int updateByPrimaryKey(Academy record);
}