package com.etc.dao;

import com.etc.entity.Attendance;
import com.etc.entity.AttendanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttendanceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int countByExample(AttendanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int deleteByExample(AttendanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int insert(Attendance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int insertSelective(Attendance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	List<Attendance> selectByExample(AttendanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	Attendance selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Attendance record, @Param("example") AttendanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int updateByExample(@Param("record") Attendance record, @Param("example") AttendanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int updateByPrimaryKeySelective(Attendance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attendance
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int updateByPrimaryKey(Attendance record);
}