package com.etc.dao;

import com.etc.entity.Classes;
import com.etc.entity.ClassesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classes
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int countByExample(ClassesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classes
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int deleteByExample(ClassesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classes
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classes
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int insert(Classes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classes
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int insertSelective(Classes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classes
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	List<Classes> selectByExample(ClassesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classes
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	Classes selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classes
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Classes record, @Param("example") ClassesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classes
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int updateByExample(@Param("record") Classes record, @Param("example") ClassesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classes
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int updateByPrimaryKeySelective(Classes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classes
	 * @mbggenerated  Tue Jul 24 19:37:17 CST 2018
	 */
	int updateByPrimaryKey(Classes record);
}